### ISSUE TITLE
Requests are sent to printer 2x (twice) - Solved

### ISSUE THREAD

**Issue by digiglee** [PrintNode/PrintNode-Java#3]
APIClient.java has a method called "createPrintJob" which passes PrintJobJson as a parameter. This file (PrintJobJson.java) has a varible qty = -1 which was sending the requests twice. 
I changed it to 1 and now I'm getting only one copy.

**Comment by PrintNodeJames** [comment]
Hi Nanbs,

Thanks for spotting and fixing this issue. I’ve made the change to the code and closed the issue.

Thanks,

James
